### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by jms136** [SingularityMan/vector_stock_market_bot#1]
when trying to python main.py this is the error I get

Traceback (most recent call last):
  File "C:\Users\jmsja\vector_stock_market_bot\main.py", line 147, in <module>
    login = r.login(username, password, expiresIn=60*60*12)
  File "C:\Users\jmsja\vector_stock_market_bot\lib\site-packages\robin_stocks\robinhood\authentication.py", line 197, in login
    raise Exception(data['detail'])
Exception: Please enter a valid email address.

**Comment by SingularityMan** [comment]
> when trying to python main.py this is the error I get
> 
> Traceback (most recent call last): File "C:\Users\jmsja\vector_stock_market_bot\main.py", line 147, in login = r.login(username, password, expiresIn=60_60_12) File "C:\Users\jmsja\vector_stock_market_bot\lib\site-packages\robin_stocks\robinhood\authentication.py", line 197, in login raise Exception(data['detail']) Exception: Please enter a valid email address.

You're supposed to include your username and password in your environment variables in order to access it directly. Otherwise, you'd have to type in your username and password when prompted.

The script thinks your username and password are present, so its locating _something_ but whatever its retrieving doesn't seem to be your email address. Did you type in your email address/variable name correctly?

**Comment by jms136** [comment]
thanks for the quick response! i just figured it out thought i had my literal username in the variable not my email address. ONe more question since your online though, how does ollama play into this? i cant see where it actually starts the ollama model and uses it?

**Comment by SingularityMan** [comment]
> thanks for the quick response! i just figured it out. I had my literal username in the variable not my email address. One more question since your online though, how does ollama play into this? I cant see where it actually starts the ollama model and uses it?

Take a close look at the first function declaration: `run()`. The API call is there. The remaining functions use `run()` afterwards to make their decisions.

**Comment by jms136** [comment]
so you swap to whatever you want by simply rewriting line 39 of python main.py with the correct model? thanks so much for the help! im just now starting my python/ollama/ computer programing journey and this is the first project i chose

**Comment by SingularityMan** [comment]
> so you swap to whatever you want by simply rewriting line 39 of python main.py with the correct model? thanks so much for the help! im just now starting my python/ollama/ computer programing journey and this is the first project i chose

Yes! You may swap out that model with whatever model supported by Ollama in line 39 of main.py! This script is designed to run as is, so you don't need to change anything if you just want it to run. However, if you want to change the model, change line 39. If you want to modify your portfolio, change `ticker_list` in line 174.

**_WARNING: DO NOT PERFORM ANY MANUAL TRADES ON ROBINHOOD IF YOUR TICKER IS INCLUDED IN TICKER_LIST. THIS COULD TRIGGER A DAY TRADE AND COULD LOCK YOU OUT OF DAY TRADING ON MARGIN/ROBINHOOD_INSTANT._**

Look it up if you don't know what that is. Good luck!

**Comment by jms136** [comment]
Thanks so much!

**Comment by SingularityMan** [comment]
> Thanks so much!

No problem bud. Happy Election Night!

**Comment by jms136** [comment]
Man would you ever consider building a bot similar to the vector bot, but for crypto on Robinhood?

**Comment by SingularityMan** [comment]
> Man would you ever consider building a bot similar to the vector bot, but for crypto on Robinhood?

I haven't tried crypto but if I'm not mistaken you may be able to perform transactions with crypto Tickers and just putting them in the ticker_list portfolio in the script.
